### ISSUE TITLE
Despite ChangeDisplayname/ChangeListname player name changes to twitch name

### ISSUE THREAD

**Issue by fahlur** [DeliciousJaffa/MultiTwitchWhitelist-plugin#2]
what the title says. Latest version of the plugin. Both values are false. players names are changing to twitch names.

**Comment by DeliciousJaffa** [comment]
Have you reloaded your config file or restarted the server since changing your settings?
This absolutely can't happen unless bukkit's config system is saying that option is true

See:
https://github.com/DeliciousJaffa/MultiTwitchWhitelist-plugin/blob/master/src/cat/jaffa/multitwitchwhitelist/LoginListener.java#L22-L27
https://github.com/DeliciousJaffa/MultiTwitchWhitelist-plugin/blob/master/src/cat/jaffa/multitwitchwhitelist/LoginListener.java#L95-L100

**Comment by fahlur** [comment]
Thank you. i managed to figure out what may have happened. made sure the config is as it was suppose to be. reloaded it, for some reason didnt work the first time even with the relog. but after the 2nd it worked. dunno what happened there.
